name: Tests
on:
  push:
    branches: [ master, develop, develop-4.0.0 ]
  pull_request:
    branches: [ master, develop, develop-4.0.0 ]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Versions
        run: vim --version
      - name: Run tests
        run: |
          git clone https://github.com/thinca/vim-themis
          ./vim-themis/bin/themis
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Versions
        run: vim --version
      - name: Run tests
        run: |
          git clone https://github.com/thinca/vim-themis
          ./vim-themis/bin/themis
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Versions
        run: vim --version
      - name: Run tests
        shell: cmd
        run: |
          git clone https://github.com/thinca/vim-themis
          bash -c "./vim-themis/bin/themis"
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Versions
        run: vim --version
      - name: Run tests
        run: |
          # TL;DR:
          # Run helptags doc
          # If an error happens, the try-catch catches it. Echoerr v:exception then logs it
          # and aborts the rest of that command. If it doesn't error, the `qa` is executed,
          # and vim exits normally, resulting in the last -c not being executed.
          # The last -c is only executed if an error occurs, and cq is exiting vim with an error,
          # which causes the CI to observe teh error as well, and causing a proper CI failure.
          # Stonks!
          vim -c "try | helptags doc | catch | echoerr v:exception | endtry | qa" -c "cq"
